version: '3.8'

volumes:
  postgres_data: {}

services:
  postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    environment:
      NODE_ENV: production
      DB_HOST: postgres
    depends_on:
      - postgres
    volumes:
      - .:/app
      - /app/node_modules
      - ./.env:/app/.env
    command: ["./docker-entrypoint.sh"]